stages:
  - build
  - deploy

.common:
  allow_failure: false
  only:
    - master
  variables:
    APP_PORT: "${APP_PORT}"
    APP_USER: "${APP_USER}"
    APP_BCRYPT_PW: "${APP_BCRYPT_PW}"
    APP_SECRET: "${APP_SECRET}"

before_script:
  - docker login -u ${CI_REGISTRY_USER} -p ${CI_REGISTRY_PASSWORD} ${CI_REGISTRY}

build:
  # image: docker:19.03.12
  # services:
  #  - docker:19.03.12-dind
  stage: build
  script:
    - docker build --pull . -t ${CI_REGISTRY}/go/shorty
    - docker push ${CI_REGISTRY}/go/shorty

deploy:
  stage: deploy
  when: manual
  script:
    - docker stop shorty
    - docker pull ${CI_REGISTRY}/go/shorty
    - docker run
      -d
      --name shorty
      -e APP_PORT="${APP_PORT}"
      -e APP_USER="${APP_USER}"
      -e APP_BCRYPT_PW="${APP_BCRYPT_PW}"
      -e APP_SECRET="${APP_SECRET}"
      -v /opt/volumes/shorty:/data
      -p "127.0.0.1:${APP_PORT}:${APP_PORT}"
      ${CI_REGISTRY}/go/shorty
