stages:
  - build
  - deploy

.common:
  allow_failure: false
  only:
    - master

before_script:
  - docker login -u ${CI_REGISTRY_USER} -p ${CI_REGISTRY_PASSWORD} ${CI_REGISTRY}

build:
  stage: build
  script:
    - docker build --pull . -t ${CI_REGISTRY}/go/shorty
    - docker push ${CI_REGISTRY}/go/shorty

deploy:
  stage: deploy
  when: manual
  script:
    - docker stop shorty || true && docker rm shorty || true
    - docker pull ${CI_REGISTRY}/go/shorty
    - docker run
      -d
      --name shorty
      -e APP_PORT="${APP_PORT}"
      -e APP_USER="${APP_USER}"
      -e APP_BCRYPT_PW="${APP_BCRYPT_PW}"
      -e APP_SECRET="${APP_SECRET}"
      -v ${APP_VOLUME_PATH}:/data
      -p "127.0.0.1:${APP_PORT}:${APP_PORT}"
      --restart unless-stopped
      ${CI_REGISTRY}/go/shorty
