version: "3.7"

services:
  app:
    container_name: shorty_app_dev
    build:
      context: .
      target: dev
    volumes:
      - ./data:/data
      - ./src:/app
      - /app/assets/node_modules
    ports:
      - "127.0.0.1:3000:3000"
    env_file: ./.env.local
    command: sh -c "cd assets && npm i && npm run build && cd /app && fresh -c /runner.conf"
